# Python code to catch an exception and handle it using try and except code blocks  
a = ["Python", "Exceptions", "try and except"]  
try:  
    print(a[0])
    print(a[1])
    print(a[2])
    print(a[3])
    print("inner end of the code")
except:
    print ("Index out of range") 
print("end of the code") 
print("end of the code") 
print("end of the code") 
print("end of the code") 